version: "3.9"
services:
    web:
        image: node:14-slim
        working_dir: /usr/src/app
        environment:
            PORT: 8080
            SPOTIFY_CLIENT_ID: your-client-id
            SPOTIFY_CLIENT_SECRET: your-client-secret
            SPOTIFY_REDIRECT_URI: http://localhost:8080/callback
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/src/app
        command: bash -c "npm install && npm run dev"
