name: Deploy to Google Cloud Run
on:
    push:
        branches: [ gcp-cloud-run ]
jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup Cloud SDK
                uses: google-github-actions/setup-gcloud@master
                with:
                    project_id: ${{ env.PROJECT_ID }}
                    service_account_email: ${{ secrets.GCP_EMAIL }}
                    service_account_key: ${{ secrets.GCP_CREDENTIALS }}
                    export_default_credentials: true  # Set to true to authenticate the Cloud Run action
            -   name: Authorize Docker push
                run: gcloud auth configure-docker
            -   name: Build container
                run: docker build -t $IMAGE_NAME .
            -   name: Push Docker image
                run: docker push $IMAGE_NAME
            -   name: Deploy to Cloud Run
                id: deploy
                uses: google-github-actions/deploy-cloudrun@main
                with:
                    service: ${{ secrets.GCP_APP_NAME }}
                    image: ${{ env.IMAGE_NAME }}
                    region: ${{ secrets.GCP_REGION }}
                    env_vars: SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }},SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }},SPOTIFY_REDIRECT_URI=${{ secrets.SPOTIFY_REDIRECT_URI }}
